### ISSUE TITLE
Bug image

### ISSUE THREAD

**Issue by nikkyb8** [infostreams/excel-merge#6] opened 2017-08-28 16:19 UTC
Hello,

When I try to merge my file I get this error ...
Can you tell me why?

thank you in advance
[fist.xlsx](https://github.com/infostreams/excel-merge/files/1257463/fist.xlsx)
[seconde.xlsx](https://github.com/infostreams/excel-merge/files/1257464/seconde.xlsx)

**Comment by nikkyb8** [comment] 2017-08-28 16:30
I have corrected this: if (count($elems) > 1 && $elems->item(0)->hasChildNodes()) {

By cons on the output file, I have the image that on the 1st page with an error at the opening (see pj).

[my-filename-2.xlsx](https://github.com/infostreams/excel-merge/files/1257497/my-filename-2.xlsx)

cordially

**Comment by infostreams** [comment] 2017-08-29 13:25
Hi, I'm sorry that you have run into this problem. The problem is that I didn't explicitly add support for images, because I didn't need it myself. So in a way, this is not a bug, it's a lack of a feature 😐

Unfortunately, I don't have time now or in the near future to write this code. I barely have enough time to finish my paid projects, let alone my unpaid (open source) projects. I did correct the bug you found in the Styles.php file mentioned above, but the bigger issue (that merging these two files results in a broken file) is not addressed yet.

What you can try is adding an intermediate step and pass these two files through PHPExcel first. Basically you first read them with PHPExcel and then immediately write them out again. Seems that 'native' Excel files result in errors, and I don't know why. Not sure if this will help you though.

Good luck! And apologies that I can't be more helpful at this point.

**Comment by infostreams** [comment] 2018-02-15 09:35
If anyone wants to address this, please be my guest. I don't have time to implement it myself, unfortunately, so I'm closing this issue.

**Closed by infostreams** 2018-02-15 09:35 UTC
