### ISSUE TITLE
Got error Undefined offset: 164

### ISSUE THREAD

**Issue by minkbear** [infostreams/excel-merge#2] opened 2016-07-22 15:14 UTC
Please advice.

```
[ErrorException]
Undefined offset: 164
```

Here is trace:
```
 () at C:\vendor\infostreams\excel-merge\Tasks\Styles.php:175
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at C:\vendor\infostreams\ex
cel-merge\Tasks\Styles.php:175
 ExcelMerge\Tasks\Styles->rewriteCells() at C:\vendor\infostreams\excel-merge\Tasks\Styles.p
hp:51
 ExcelMerge\Tasks\Styles->merge() at C:\vendor\infostreams\excel-merge\ExcelMerge.php:134
 ExcelMerge\ExcelMerge->mergeWorksheets() at C:\vendor\infostreams\excel-merge\ExcelMerge.ph
p:55
 ExcelMerge\ExcelMerge->addFile() at C:\vendor\infostreams\excel-merge\ExcelMerge.php:40
```

I am using PHP 7.0.4 with Laravel 5.2

**Comment by infostreams** [comment] 2016-07-22 17:05
It's hard to say what is wrong with it, but it looks like it is trying to access something that doesn't exist. I wrote some code that first checks if the thing exists. It should make this error go away, but I'm not sure if it will then produce a correct Excel file – for that I need more information, such as which two files you're trying to merge.

Please let me know if this fixes your problem.

**Comment by minkbear** [comment] 2016-07-23 04:00
Thanks for your fast response.
I will give you two sample of files in the next couple days.

**Comment by infostreams** [comment] 2016-07-23 04:32
Did the new version not fix the problem?

**Comment by minkbear** [comment] 2016-07-23 04:49
Ahhh... Sorry my mistake. I will try a new release and back to you.

**Comment by minkbear** [comment] 2016-07-23 05:20
No error anymore but there is no file output as expected when calling save.

My parameter path is:

"C:\test\storage\report/sm\sm_25597213.xlsx"

**Comment by infostreams** [comment] 2016-07-23 05:30
Ok, that doesn't make any sense. Can you just attach or make available the files you're trying to merge, along with the code you've written to do that? I can have a look after the weekend.

**Comment by minkbear** [comment] 2016-07-23 06:00
please download sample files here: https://dl.dropboxusercontent.com/u/17863424/excel_merge_2.zip

```
$files = [
'C:\test\storage\report/sm\sample_1.xlsx', 
'C:\test\storage\report/sm\sample_2.xlsx'
];
$merged = new ExcelMerge($files);
$filename = $merged->save('c:\test\storage\report/sm\test_merge.xlsx');
```

Thank you.

**Comment by infostreams** [comment] 2016-07-25 14:10
Hi! I could reproduce your issue, but I couldn't fix it. I could work around it, though. 

I suspect the issue is that these are files that are created by a 'real' version of Excel, and this library was originally written to deal with Excel files generated by PHPExcel. I don't know why it doesn't seem to work properly with normal Excel files, but apparently they are slightly different and that confuses this library.

Nevertheless, if you want to work around this issue and get a mostly functioning, mostly correct output file:

First, do

```composer require PHPOffice/PHPExcel```

Then, use the following code instead of the code you provided

```php
require_once("vendor/autoload.php");

$files = [
	'data/sample_1.xlsx',
	'data/sample_2.xlsx'
];

foreach ($files as $i=>$f) {
	$objReader = PHPExcel_IOFactory::createReader("Excel2007");
	$objPHPExcel = $objReader->load($f);

	// Write the file
	$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, "Excel2007");
	$filename_new = $f . ".new.xlsx";
	$objWriter->save($filename_new);

	$files[$i] = $filename_new;
}

$merged = new ExcelMerge\ExcelMerge($files);
$filename = $merged->save('test_merge.xlsx');
```

Excel still gives a warning when opening the output file, but it contains all the information and seems to be mostly correct upon first glance.

I'm closing this issue because the README clearly states that the library has a problem with 'native' Excel files, that I don't know the reason, and that I don't have proper time to look into it. If you know why it's failing, or if you figure out how to fix it, please contribute to the development of this library and open a pull request. Thanks!

**Closed by infostreams** 2016-07-25 14:10 UTC

**Comment by minkbear** [comment] 2016-07-27 19:01
Thank you much for your response.
