### ISSUE TITLE
Excel with images

### ISSUE THREAD

**Issue by firomero** [infostreams/excel-merge#9] opened 2018-08-08 21:15 UTC
When merging excel with images, it doesn't add the images.
Tested on php7.0 and ubuntu 1604
best regards

**Comment by infostreams** [comment] 2018-08-14 10:35
Duplicate of #6 - see https://github.com/infostreams/excel-merge/issues/6#issuecomment-325662632

**Closed by infostreams** 2018-08-14 10:35 UTC
